---
- name: Generate password
  include_vars: root_password.yml
- name: Set root password
  shell: mysql -e "UPDATE mysql.user SET Password=PASSWORD('{{ mariadb_root_password }}') WHERE User='root';"
- name: Remove anonymous users
  shell: mysql -e "DELETE FROM mysql.user WHERE User='';"
  ignore_errors: yes
- name: Remove non-local root users
  shell: mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
  when: not mariadb_remote_root_access
  ignore_errors: yes
- name: Remove test database
  shell: mysql -e "DROP DATABASE test;"
  ignore_errors: yes
- name: Remove privileges on test database
  shell: mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
  ignore_errors: yes
- name: Reload privileges
  shell: mysql -e "FLUSH PRIVILEGES;"
- name: Configure root profile
  template: src=my.cnf dest={{ mariadb_client_config }} owner=root group=root mode=0600
            backup=yes
